### PR TITLE
Mock system responses

### PR DESCRIPTION
**Pull request by tomhosiawa**

### CODE REVIEW

**Review by jbeanz — APPROVED** [review]
Great job! In ProcessCommand, would it be useful to split user input into an array, and check if array[0] == 'mkdir'?

**Comment by tomhosiawa** [comment]
Thanks! When we replace the mock api to the system api, I'm assuming we would
1. Sanitize the input
2. Pass the commend to the system
3. Let the system handle the request as needed (i.e. mkdir will do different checks than ls)
4. Present the raw output from the system to the user

If the above is true, does it still make sense to check the first item in the array (i.e. we'll never do this for real system api)?

**Comment by tomhosiawa** [comment]
Btw,

**Comment by tomhosiawa** [comment]
Btw, Sean told me the system api requires is as you described (tokenized). My assumption was wrong

**Pull request merged**
